# Generated by Django 5.0.1 on 2024-01-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModelName',
            new_name='Product',
        ),
    ]
